# Role: os
network:
  ip: "{{ host.ip }}"
  gateway: "192.168.11.1"
  dns: "192.168.11.2, 192.168.11.3"
  subnet_cidr: "24"
  domain: "jrhorner.com"

# Role: common
common_upgrade_packages: true
common_reboot_handler_enabled: true
common_timezone: America/New_York
# common_usb_ssd_enabled: false
# common_usb_ssd_device_id: ""
# common_rpi_overclock: false
common_rpi_poe_hat: true
common_log2ram_enabled: false
# common_log2ram_version: v1.4
# common_log2ram_size: 128M

# Role: registry_mirror
registry_mirror_enable: true
registry_mirror_fqdn: "registry.jrhorner.com"
registry_mirror_tls_enable: true

# Role: cri
cri_plugin: cri-o
# CRI-O Specific
crio_os: "xUbuntu_20.04"
crio_version: "1.20"

# Role: kubernetes
kubernetes_kubectl_version: 1.20.2-00
kubernetes_kubelet_version: 1.20.2-00
kubernetes_kubeadm_version: 1.20.2-00

# Role: storage
openebs_enabled: true