---
- name: 'validate variable : keepalived_vip'
  assert:
    that:
      - keepalived_vip | ipaddr
    fail_msg:
      - "Variable 'keepalived_vip' should be a valid ip address"
      - 'Type is: {{ keepalived_vip | type_debug }}'
      - "Value is: {{ keepalived_vip | default('undefined') }}"

- name: 'debian : install haproxy'
  apt:
    name: haproxy
    install_recommends: false
    update_cache: true
    force_apt_get: true
  register: apt_install_haproxy
  retries: 5
  until: apt_install_haproxy is success
  when: ansible_os_family | lower == 'debian'

- name: haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: set sysctl net.ipv4.ip_nonlocal_bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/ip_nonlocal_bind.conf
    state: present
  notify: restart haproxy