---
# - name: check if k3s is installed 

- name: add memory cgroup settings to cmdline.txt
  template:
    src: cmdline.txt.j2
    dest: /boot/firmware/cmdline.txt
    owner: root
    group: root
    mode: 0644
  register: mem_cgroup

- name: reboot if memory cgroup set
  command: reboot now
  when: mem_cgroup is changed

- name: reconnect
  wait_for:
    port: 22
  
- name: download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    owner: root
    group: root
    mode: 0755

- name: install k3s | master
  shell:  /tmp/k3s_install.sh >> /var/log/k3s_install.log
  environment:
    INSTALL_K3S_SKIP_START: true
  when: k3s.master is true

- name: install k3s | worker
  shell:  /tmp/k3s_install.sh >> /var/log/k3s_install.log
  environment:
    INSTALL_K3S_SKIP_START: true
    K3S_URL: "{{ k3s_cluster_url }}"
    K3S_TOKEN: "{{ k3s_cluster_token }}"
  when: k3s.worker is true

- name: setup defaults and service
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: "k3s.defaults.j2"
      dest: "/etc/default/k3s"
    - src: "k3s.service.j2"
      dest: "/etc/systemd/system/k3s.service"
  notify: restart k3s
  when: k3s.master is true
  tags: k3s-config