---
- name: 'validate variable : keepalived_interface'
  assert:
    that:
      - (keepalived_interface | type_debug == 'AnsibleUnicode') or (keepalived_interface | type_debug == 'AnsibleUnsafeText')
      - keepalived_interface | length > 0
    fail_msg:
      - "Variable 'keepalived_interface' should be set and of type 'AnsibleUnicode' (string)"
      - 'Type is: {{ keepalived_interface | type_debug }}'
      - "Value is: {{ keepalived_interface | default('undefined') }}"

- name: 'validate variable : keepalived_vip'
  assert:
    that:
      - keepalived_vip | ipaddr
    fail_msg:
      - "Variable 'keepalived_vip' should be a valid ip address"
      - 'Type is: {{ keepalived_vip | type_debug }}'
      - "Value is: {{ keepalived_vip | default('undefined') }}"

- name: 'install keepalived'
  apt:
    name: keepalived
    install_recommends: false
    update_cache: true
    force_apt_get: true
  register: apt_install_keepalived
  retries: 5
  until: apt_install_keepalived is success
  when: ansible_os_family | lower == 'debian'

- name: generate keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived