---
- hosts: 127.0.0.1
  connection: local
  vars:
    local_authorized_keys: "../../ssd_prep/.ssh/authorized_keys"

  tasks:
    - name: ensure authorized_keys file exists
      ansible.builtin.stat:
        path: "{{ local_authorized_keys }}"
      register: ak

    - name: create authorized_keys file
      ansible.builtin.file:
        path: "{{ local_authorized_keys }}"
        state: touch
      when: not ak.stat.exists

    - name: populate authorized_keys file
      ansible.posix.authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        path: "{{ local_authorized_keys }}"
        key: "{{ lookup('file', item) }}"
        state: present
        manage_dir: false
      with_fileglob: "../files/public_keys/*.pub"
