---
- hosts: masters,workers
  become: yes
  serial: 1
  tasks: 
    - name: reboot hosts
      reboot:
        msg: "RPi's are being rebooted"
        reboot_timeout: '{{ reboot_timeout | default(600) }}'