---
- hosts: all
  tasks:
    - name: Add SSH public keys to host
      ansible.posix.authorized_key:
        user: "ubuntu"
        key: "{{ lookup('file', item) }}"
        state: present
      with_fileglob: "../files/public_keys/*.pub"
      tags: [ always, add ]

    - name: Remove SSH public keys from host
      ansible.posix.authorized_key:
        user: "ubuntu"
        key: "{{ lookup('file', item) }}"
        state: absent
      loop:
        - "../files/public_keys/id_rsa.pub"
      tags: [ never, remove ]